apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild:
    projectId: ticketing-dev-304614 
  artifacts:
    - image: us.gcr.io/ticketing-dev-304614/auth
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.ts'
            dest: .
    - image: us.gcr.io/ticketing-dev-304614/client
      context: client
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: '***/*.js'
            dest: .